### ISSUE TITLE
Dependencies to declare?

### ISSUE THREAD

**Issue by andk** [robrwo/File-Rotate-Simple#8]
A grep shows they are in use but not mentioned anywhere else: http://search.cpan.org/grep?release=File-Rotate-Simple-v0.2.0;string=Graph|Moo|Test::Most;n=1;C=0

Fail reports show the missing declarations lead to failing tests:

http://www.cpantesters.org/cpan/report/89815489 | Graph.pm
http://www.cpantesters.org/cpan/report/89817012 | Moo.pm
http://www.cpantesters.org/cpan/report/89852441 | Test/Most.pm

**Comment by robrwo** [comment]
Seems to be a hiccup with (mis)use of Dist::Zilla. Thanks.

**Comment by robrwo** [comment]
This should be fixed in v0.2.1.
